animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

print "1 Python", animals[1]
print "2 Peacock", animals[2]
print "3 Bear", animals[0]
print "4 Kangaroo", animals[3]
print "5 Whale", animals[4]
print "6 Peacock", animals[2]
print "7 Platypus", animals[5]
print "8 Whale", animals[4]